version: '3.3'

services:
  mysql:
    image: mysql
    volumes:
      - ./.data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  nginx:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    ports:
      - "13080:80"
    volumes:
      - ./.config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.config/nginx/conf.d:/etc/nginx/conf.d
      - ./.data/nginx:/var/log/nginx
      - ./html:/var/www/html

  php:
    build:
      context: ./
      dockerfile: php.dockerfile
    depends_on:
      - nginx
      - mysql
    links:
      - mysql
    volumes:
      - ./.config/php/php.ini:/usr/local/etc/php/php.ini
      - ./.config/php/config.d:/usr/local/etc/php/config.d
